test_that("changepoint works", {
  x <- segment(DataCPSim, method = "pelt")
  expect_s3_class(x, "tidycpt")
  expect_s4_class(x$segmenter, "cpt")
  expect_s3_class(as.ts(x), "ts")
  expect_s3_class(augment(x), "grouped_ts")
  expect_s3_class(tidy(x), "tbl_df")
  expect_s3_class(glance(x), "tbl_df")
  expect_type(changepoints(x), "integer")
  expect_s3_class(logLik(x$segmenter), "logLik")
  expect_type(fitness(x$segmenter), "double")
  expect_equal(names(fitness(x$segmenter)), "MBIC")
  expect_gt(fitness(x), changepoint::pen.value(x$segmenter))
#  expect_equal(fitness(x), MBIC(x$model))
  expect_true(is_segmenter(x$segmenter))
  expect_true(is_model(x$model))
  
  y <- segment(DataCPSim, method = "pelt", penalty = "BIC")
  expect_equal(as.double(logLik(y$segmenter)), as.double(logLik(y$model)))
  expect_equal(unname(fitness(y)), BIC(y$model))
  
  x <- segment(DataCPSim, method = "binseg")
  expect_s3_class(x, "tidycpt")
  expect_s4_class(x$segmenter, "cpt")
  expect_s3_class(as.ts(x), "ts")
  expect_s3_class(augment(x), "grouped_ts")
  expect_s3_class(tidy(x), "tbl_df")
  expect_s3_class(glance(x), "tbl_df")
  expect_type(changepoints(x), "integer")
})
