test_that("changepoint works", {
  x <- segment(DataCPSim, method = "cpt-pelt")
  expect_s3_class(x, "tidycpt")
  expect_s4_class(x$segmenter, "cpt")
  expect_s3_class(as.ts(x), "ts")
  expect_s3_class(augment(x), "grouped_ts")
  expect_s3_class(tidy(x), "tbl_df")
  expect_s3_class(glance(x), "tbl_df")
  expect_type(changepoints(x), "integer")
  
  x <- segment(DataCPSim, method = "cpt-binseg")
  expect_s3_class(x, "tidycpt")
  expect_s4_class(x$segmenter, "cpt")
  expect_s3_class(as.ts(x), "ts")
  expect_s3_class(augment(x), "grouped_ts")
  expect_s3_class(tidy(x), "tbl_df")
  expect_s3_class(glance(x), "tbl_df")
  expect_type(changepoints(x), "integer")
})
