test_that("seg_default works", {
  x <- segment(DataCPSim)
  expect_s3_class(x, "tidycpt")
  expect_s3_class(x$segmenter, "seg_default")
  expect_s3_class(as.ts(x), "ts")
  expect_s3_class(augment(x), "grouped_ts")
  expect_s3_class(tidy(x), "tbl_df")
  expect_equal(nrow(tidy(x)), 1)
  suppressWarnings(expect_s3_class(glance(x), "tbl_df"))
  expect_type(changepoints(x), "integer")
  expect_equal(length(changepoints(x)), 0)  
  expect_type(nobs(x), "integer")
  expect_true(is_segmenter(x$segmenter))
  expect_true(is_model(x$model))

  expect_s3_class(evaluate_cpts(x$segmenter), "tbl_df")
  expect_s3_class(evaluate_cpts(list(), .data = DataCPSim, model_fn = fit_nhpp), "tbl_df")
  expect_s3_class(evaluate_cpts(tibble::tibble(changepoints = list(826)), .data = DataCPSim, model_fn = fit_nhpp), "tbl_df")
  
  y <- segment(DataCPSim, method = "manual", tau = c(826))
  expect_s3_class(y, "tidycpt")
  expect_s3_class(y$segmenter, "seg_default")
  expect_s3_class(as.ts(y), "ts")
  expect_s3_class(augment(y), "grouped_ts")
  expect_s3_class(tidy(y), "tbl_df")
  expect_equal(nrow(tidy(y)), 2)
  expect_s3_class(glance(y), "tbl_df")
  expect_type(changepoints(y), "integer")
  expect_equal(length(changepoints(y)), 1)
  expect_type(nobs(y), "integer")
  expect_type(fitness(y$segmenter), "double")

  z <- segment(DataCPSim, method = "manual", tau = c(365, 826))
  expect_s3_class(z, "tidycpt")
  expect_s3_class(z$segmenter, "seg_default")
  expect_s3_class(as.ts(z), "ts")
  expect_s3_class(augment(z), "grouped_ts")
  expect_s3_class(tidy(z), "tbl_df")
  expect_equal(nrow(tidy(z)), 3)
  expect_s3_class(glance(z), "tbl_df")
  expect_type(changepoints(z), "integer")
  expect_equal(length(changepoints(z)), 2)
  expect_type(nobs(z), "integer")
  expect_true(all(c("logLik", "AIC", "BIC", "MBIC", "MDL") %in% names(z$segmenter$candidates)))
})

test_that("random works", {
  x <- segment(DataCPSim, method = "random")
  expect_s3_class(x, "tidycpt")
  expect_s3_class(x$segmenter, "seg_default")
  expect_s3_class(as.ts(x), "ts")
  expect_s3_class(augment(x), "grouped_ts")
  expect_s3_class(tidy(x), "tbl_df")
  suppressWarnings(expect_s3_class(glance(x), "tbl_df"))
  expect_type(changepoints(x), "integer")
})